---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create Nginx configuration file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/drupal
    mode: '0644'
  notify: reload nginx

- name: Enable Drupal site
  file:
    src: /etc/nginx/sites-available/drupal
    dest: /etc/nginx/sites-enabled/drupal
    state: link

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx
